USER_NAME := chrisgve

LTO_ENABLE = yes
NKRO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
DEBUG_ENABLE = no
RGBLIGHT_ENABLE = no

MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
SHIFT_ENABLE = yes
