USER_NAME = chrisgve

APPLE_FN_ENABLE = no

SRC += chrisgve.c
LTO_ENABLE = yes

NKRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no

BACKLIGHT_ENABLE = yes
MODIFIERS_ENABLE = yes

TAPPING_TERM_PER_KEY = no
PERMISSIVE_HOLD_PER_KEY = no
HOLD_ON_OTHER_KEY_PRESS_PER_KEY = no
PERMISSIVE_HOLD = no
